# "athlete_id" : ,
# "date_measurement" : ,
# "data_recorder_coach" : ,
# "weight" : ,
# "fat_percentage" :,
# "around_neck" : ,
# "around_chest" : ,
# "around_arm" : ,
# "waist_circumference" : ,
# "abdominal_circumference" :,
# "around_thigh" : ,
# "leg_circumference" :,
# "description" : ,
